import { GetAvatarDataCsReq, GetAvatarDataScRsp } from "../../data/proto/StarRail";
import AvatarExcelTable from "../../data/excel/AvatarExcelTable.json";
import Packet from "../kcp/Packet";
import Session from "../kcp/Session";

export default async function handle(session: Session, packet: Packet) {
    const body = packet.body as GetAvatarDataCsReq;

    const dataObj = {
        retcode: 0,
        avatarList: [
            {
                baseAvatarId: 1001,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1002,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1003,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1004,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1005,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1006,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1008,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1009,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1013,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1101,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1102,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1103,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1104,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1105,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1106,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1107,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1108,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1109,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1203,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1204,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 1,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1205,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
            {
                baseAvatarId: 1206,
                equipmentUniqueId: 13501,
                equipRelicList: [],
                exp: 0,
                level: 80,
                promotion: 5,
                rank: 6,
                skilltreeList: [],
            },
    ],
        isAll: body.isGetAll
    } as GetAvatarDataScRsp;

    Object.values(AvatarExcelTable).forEach(avatar => {
        // dataObj.avatarList.push()
    });

    session.send("GetAvatarDataScRsp", dataObj);
}
